/**
 * Email Service for MATIKAI Frontend
 * Handles all email automation API calls
 */

import axios from 'axios';

const API_BASE_URL = process.env.REACT_APP_BACKEND_URL || import.meta.env.REACT_APP_BACKEND_URL;

class EmailService {
  constructor() {
    this.baseURL = `${API_BASE_URL}/api/email`;
  }

  // Get authentication headers
  getAuthHeaders() {
    const token = localStorage.getItem('token');
    return {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    };
  }

  // Send single email
  async sendEmail(emailData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/send`,
        emailData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to send email:', error);
      throw error;
    }
  }

  // Send lead follow-up email
  async sendLeadFollowUp(leadData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/lead-follow-up`,
        leadData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to send lead follow-up:', error);
      throw error;
    }
  }

  // Send service confirmation email
  async sendServiceConfirmation(serviceData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/service-confirmation`,
        serviceData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to send service confirmation:', error);
      throw error;
    }
  }

  // Send quote follow-up email
  async sendQuoteFollowUp(quoteData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/quote-follow-up`,
        quoteData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to send quote follow-up:', error);
      throw error;
    }
  }

  // Send bulk emails
  async sendBulkEmail(bulkData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/bulk-send`,
        bulkData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to send bulk emails:', error);
      throw error;
    }
  }

  // Generate AI email
  async generateAIEmail(aiData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/ai-generate`,
        aiData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to generate AI email:', error);
      throw error;
    }
  }

  // Generate and send AI email
  async generateAndSendAIEmail(aiData) {
    try {
      const response = await axios.post(
        `${this.baseURL}/ai-send`,
        aiData,
        { headers: this.getAuthHeaders() }
      );
      return response.data;
    } catch (error) {
      console.error('Failed to generate and send AI email:', error);
      throw error;
    }
  }

  // Get email service status
  async getStatus() {
    try {
      const response = await axios.get(`${this.baseURL}/status`);
      return response.data;
    } catch (error) {
      console.error('Failed to get email service status:', error);
      throw error;
    }
  }

  // Email templates for different contexts
  getEmailTemplates() {
    return {
      leadFollowUp: {
        name: "Lead Follow-up",
        description: "Automated follow-up for new leads",
        fields: ['lead_name', 'lead_email', 'lead_score', 'estimated_value', 'sales_rep']
      },
      serviceConfirmation: {
        name: "Service Request Confirmation", 
        description: "Confirmation for service requests",
        fields: ['customer_name', 'customer_email', 'service_type', 'appointment_date', 'technician_name']
      },
      quoteFollowUp: {
        name: "Quote Follow-up",
        description: "Follow-up on provided quotes",
        fields: ['customer_name', 'customer_email', 'quote_amount', 'quote_id', 'valid_until', 'sales_rep']
      },
      aiGenerated: {
        name: "AI Generated Email",
        description: "Personalized email generated by AI",
        fields: ['recipient_name', 'recipient_email', 'context', 'tone', 'call_to_action', 'customer_data']
      }
    };
  }

  // Industry-specific email contexts
  getEmailContexts() {
    return [
      { value: 'lead_follow_up', label: 'Lead Follow-up' },
      { value: 'quote_follow_up', label: 'Quote Follow-up' },
      { value: 'service_appointment', label: 'Service Appointment' },
      { value: 'implementation_scheduling', label: 'Installation Scheduling' },
      { value: 'warranty_information', label: 'Warranty Information' },
      { value: 'payment_reminder', label: 'Payment Reminder' },
      { value: 'product_update', label: 'Product Update' },
      { value: 'customer_satisfaction', label: 'Customer Satisfaction Survey' }
    ];
  }

  // Email tone options
  getEmailTones() {
    return [
      { value: 'professional', label: 'Professional' },
      { value: 'friendly', label: 'Friendly' },
      { value: 'urgent', label: 'Urgent' },
      { value: 'informative', label: 'Informative' },
      { value: 'persuasive', label: 'Persuasive' },
      { value: 'supportive', label: 'Supportive' }
    ];
  }
}

export default new EmailService();